apiVersion: apps/v1
kind: Deployment
namespace: 
metadata:
  name: nginx5
  labels:
    app: MyApp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MyApp2
  template:
    metadata:
      labels:
        app: MyApp2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service3
  labels:
    app: MyApp2
spec:
  type: NodePort
  selector:
    app: MyApp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
